services:
  sabnzbd:
    image: ghcr.io/hotio/sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    networks:
      - default
      - proxy
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.routers.sabnzbd.rule: Host(`sabnzbd`)
      traefik.http.routers.sabnzbd.middlewares: trusted-ipallowlist
    volumes:
      - /containers/sabnzbd:/config
      - /downloads:/downloads

networks:
  default:
    enable_ipv6: true
  proxy:
    external: true
