version: '3'

services:
  sabnzbd:
    image: ghcr.io/hotio/sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    ports:
      - 8090:8080
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /tank/docker/sabnzbd:/config
      - /tank/downloads:/tank/downloads
