services:
  sabnzbd:
    image: ghcr.io/hotio/sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    network_mode: host
    environment:
      WEBUI_PORTS: 8090
      PUID: 995
      PGID: 995
      UMASK: 002
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.services.sabnzbd.loadbalancer.server.port: 8090
      traefik.http.routers.sabnzbd.rule: Host(`sabnzbd`)
    volumes:
      - /containers/sabnzbd:/config
      - /downloads:/downloads
      - /tank/media/movies:/tank/media/movies
      - /tank/media/tv:/tank/media/tv
      - /tank/media/music:/tank/media/music
      - /tank/media/xxx:/tank/media/xxx
