services:
  sabnzbd:
    image: ghcr.io/hotio/sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    network_mode: host
    environment:
      WEBUI_PORTS: 8090
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.services.sabnzbd.loadbalancer.server.port: 8090
      traefik.http.routers.sabnzbd.rule: Host(`sabnzbd`)
      traefik.http.routers.sabnzbd.middlewares: sabnzbd-ipallowlist
      traefik.http.middlewares.sabnzbd-ipallowlist.ipallowlist.sourcerange: >
        2a00:23c8:bda0:b310::/64,
        10.10.0.0/16,
        fdff:0205:2005::/123,
        172.16.255.0/27
    volumes:
      - /containers/sabnzbd:/config
      - /downloads:/downloads
      - /tank/media/movies:/tank/media/movies
      - /tank/media/tv:/tank/media/tv
      - /tank/media/music:/tank/media/music
      - /tank/media/xxx:/tank/media/xxx
